# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3749aefb36745c1712c68c9ff389e07d28e7e55d403e542055c1c73efd7adf91b46c4e1b1e2e07640594302329004194f1e0817ed9d7eaabf90076b25dad1baa

test:
  secret_key_base: bd341cf74a29205409a80cca4247b3f73a18d0260ee3280864558d2e1b47e75f509b84c789a666e8ec1d6d4fc52ff4e1610c7b4338f69b023257b44940369f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
